# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#
# https://stackoverflow.com/questions/39728709/using-an-alternate-complier-for-travis-ci-r-project-builds

language: R
cache: packages
warnings_are_errors: true

os:
  - linux
#  - osx

r:
  - release
#  - devel
#  - oldrel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
